table Sales
	lineageTag: f99a9050-ea20-4b4e-8842-58a02a869512

	column SalesOrderLineKey
		dataType: int64
		formatString: 0
		lineageTag: 014bdc7c-9b20-4421-b6ee-8a0e1dd47fb2
		summarizeBy: count
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: 60459c98-fe10-48a7-9558-e2d7daa59a21
		summarizeBy: count
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 5e43c10b-dd10-4e4c-aaff-663009baba9b
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: e8dcc0ea-5904-4006-94f4-55d8f3583c73
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: fc83326d-adb9-4b1c-94d0-d7c0896040bb
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: ded6e12e-062f-49ce-8fac-250244741fec
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: afbdd62f-e998-40b0-885b-57d8351eb76f
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: d0b551af-80e5-4392-a503-ded3e09442b2
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 896d2d9d-76cb-41f9-9cc2-6ba498b4b1fa
		summarizeBy: sum
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		lineageTag: fc6d84f9-5eba-4715-b545-b375b009c35c
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extended Amount'
		dataType: double
		lineageTag: 0d88d5d6-c347-4da3-9834-f3bb0967b9d4
		summarizeBy: sum
		sourceColumn: Extended Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price Discount Pct'
		dataType: int64
		formatString: 0
		lineageTag: 3fc51132-c56c-4772-a67d-823f2045a623
		summarizeBy: sum
		sourceColumn: Unit Price Discount Pct

		annotation SummarizationSetBy = Automatic

	column 'Product Standard Cost'
		dataType: double
		lineageTag: 330f530c-58aa-46e9-84f8-696f398a9a62
		summarizeBy: sum
		sourceColumn: Product Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Product Cost'
		dataType: double
		lineageTag: a2d19a89-0526-4b28-928c-6f0e9e3b165d
		summarizeBy: sum
		sourceColumn: Total Product Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Amount'
		dataType: double
		lineageTag: 1f2037be-7294-4402-b0a6-91b1d73e8b2d
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://abbott-my.sharepoint.com/personal/sasikumar_balachandran1_abbott_com/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Demo_Sales_Dataset.xlsx")),
				    #"Demo_Sales_Dataset xlsx_https://abbott-my sharepoint com/personal/sasikumar_balachandran1_abbott_com/Documents/Desktop/2025/PBI Office Hour/4  April/" = #"Filtered Rows"{[Name="Demo_Sales_Dataset.xlsx",#"Folder Path"="https://abbott-my.sharepoint.com/personal/sasikumar_balachandran1_abbott_com/Documents/Desktop/2025/PBI Office Hour/4. April/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Demo_Sales_Dataset xlsx_https://abbott-my sharepoint com/personal/sasikumar_balachandran1_abbott_com/Documents/Desktop/2025/PBI Office Hour/4  April/"),
				    Sales_Sheet = #"Imported Excel Workbook"{[Item="Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

