table Territory2
	lineageTag: 096db830-0780-4fbd-95c3-326f1cd80918

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: dca03196-34ab-46bc-8cd1-8fbd7856d7b3
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 62d735f9-0f64-443c-b7d2-fbe57059b485
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: b2f5e37b-9399-40fb-b7ec-6e521a880ae8
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: a8e31907-ee02-4c1c-84e9-c30ea72f44a6
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	partition Territory2 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\BALACSX1\OneDrive - Abbott\Desktop\2025\PBI Office Hour\4. April\Demo_Sales_Dataset.xlsx"), null, true),
				    Territory_Table = Source{[Item="Territory",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Territory_Table,{{"SalesTerritoryKey", Int64.Type}, {"Region", type text}, {"Country", type text}, {"Group", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

